//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DanhGia
    {
        public int danhgiaID { get; set; }
        public Nullable<int> dthID { get; set; }

        [Required(ErrorMessage = "This field cannot be blank!")]
        public Nullable<int> IDCT { get; set; }

        [Required(ErrorMessage = "This field cannot be blank!")]
        [Range(0, 2000000000, ErrorMessage = "This field range cannot be smaller than 0!")]
        public Nullable<int> HoDan { get; set; }

        [Required(ErrorMessage = "This field cannot be blank!")]
        [Range(0, 2000000000, ErrorMessage = "This field range cannot be smaller than 0!")]
        public Nullable<int> HoNgheo { get; set; }

        [Required(ErrorMessage = "This field cannot be blank!")]
        public string LoaihinhQL { get; set; }

        [Required(ErrorMessage = "This field cannot be blank!")]
        public bool ThuphiDV { get; set; }

        [Required(ErrorMessage = "This field cannot be blank!")]
        public bool DatQCVN { get; set; }

        [Required(ErrorMessage = "This field cannot be blank!")]
        public bool KhaNangCapNuoc { get; set; }

        [Required(ErrorMessage = "This field cannot be blank!")]
        public bool TyLeDauNoi { get; set; }

        [Required(ErrorMessage = "This field cannot be blank!")]
        public bool CanboQL { get; set; }
    
        public virtual DataHuyen DataHuyen { get; set; }
        public virtual QLCongTrinh QLCongTrinh { get; set; }
    }
}
