//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLCNEntities : DbContext
    {
        public QLCNEntities()
            : base("name=QLCNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<DataHuyen> DataHuyens { get; set; }
        public virtual DbSet<LoaiCongTrinh> LoaiCongTrinhs { get; set; }
        public virtual DbSet<QLHuyen> QLHuyens { get; set; }
        public virtual DbSet<QLTinh> QLTinhs { get; set; }
        public virtual DbSet<QLXa> QLXas { get; set; }
        public virtual DbSet<DanhGia> DanhGias { get; set; }
        public virtual DbSet<QLCongTrinh> QLCongTrinhs { get; set; }
    }
}
