//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class QLXa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QLXa()
        {
            this.QLCongTrinhs = new HashSet<QLCongTrinh>();
        }
    
        public int ID { get; set; }

        [Required(ErrorMessage = "This field cannot be blank!")]
        public Nullable<int> IDHuyen { get; set; }

        [Required(ErrorMessage = "This field cannot be blank!")]
        public string TenXa { get; set; }

        [Required(ErrorMessage = "This field cannot be blank!")]
        public Nullable<int> IDTinh { get; set; }
    
        public virtual QLHuyen QLHuyen { get; set; }
        public virtual QLTinh QLTinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QLCongTrinh> QLCongTrinhs { get; set; }
    }
}
